title: Goal Tracker
description: Tracking the goals for those we want to hold accountable.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

markdown: kramdown
minify: true

goal_types:
    - unfinished
    - wip
    - achieved
    - failed
topics:
    - Civil Liberties
    - Environment
    - Government

exclude:
    - ".*" # Automatic, but just in case
    - "*.log"
    - "*.sh"
    - "Gemfile*"
    - "DOCUMENTATION.md"
    - "README.md"
    - "s3_website.yml"
    - "node_modules/"
